import test from 'node:test';import assert from 'node:assert/strict';
import {evaluate,defaultRules,readiness,reconcile,canonical,requisitionKey,companyGroup,nyDay,safeCsv,activeApplicationBlock,claimableApplication} from '../lib/domain.ts';
const at=new Date().toISOString();const check={value:'pass',evidence:'Official evidence verified for the candidate',source:'https://jobs.ashbyhq.com/example/id',checkedAt:at};const valid={active:'active',checkedAt:at,salaryMin:90000,checks:Object.fromEntries(['us','fulltime','timing','base','experience','degree','authorization'].map(k=>[k,{...check}]))};
test('submission receipt supersedes a previous verification-code blocker',()=>{const a={status:'uncertain',blockReason:'Enter email verification code'};assert.equal(activeApplicationBlock(a),a.blockReason);for(const status of ['submitted','assessment','interview','offer','rejected','withdrawn'])assert.equal(activeApplicationBlock({...a,status}),'');assert.equal(activeApplicationBlock({status:'blocked'}),'')});
test('salary uses confirmed base lower bound; total compensation and unknown do not pass',()=>{assert.equal(evaluate(valid,defaultRules).state,'ready');for(const j of [{...valid,salaryMin:89999},{...valid,salaryMin:null},{...valid,checks:{...valid.checks,base:{...check,value:'unknown'}}}])assert.notEqual(evaluate(j,defaultRules).state,'ready')});
test('sponsorship unknown can pass; explicit incompatible authorization fails',()=>{assert.equal(evaluate({...valid,checks:{...valid.checks,authorization:{value:'unknown'}}},defaultRules).state,'ready');assert.equal(evaluate({...valid,checks:{...valid.checks,authorization:{...check,value:'fail'}}},defaultRules).state,'excluded')});
test('active HTTP is insufficient, evidence and freshness are mandatory',()=>{for(const j of [{...valid,active:'unknown'},{...valid,checkedAt:'2020-01-01'},{...valid,checks:{...valid.checks,timing:{value:'pass'}}}])assert.notEqual(evaluate(j,defaultRules).state,'ready')});
test('no claims or authorization inferred from planned OPT',()=>{assert.ok(readiness({confirmed:false},defaultRules,[]).length>=4)});
test('event chronology, terminal conflicts and silence never infer rejection',()=>{assert.equal(reconcile('interview','submitted',at,'2020-01-01').accept,false);assert.equal(reconcile('interview','rejected','2020-01-01',at).accept,false);assert.equal(reconcile('offer','rejected',at,at).accept,false);assert.equal(reconcile('submitted','interview',at,'2020-01-01').accept,true)});
test('canonical dedup keeps requisition IDs but removes tracking',()=>{assert.equal(canonical('https://boards.greenhouse.io/acme/jobs/123?gh_src=abc'),canonical('https://job-boards.greenhouse.io/acme/jobs/123'));assert.equal(canonical('https://boards.greenhouse.io/acme/jobs/123?gh_jid=123'),canonical('https://job-boards.greenhouse.io/acme/jobs/123'));assert.equal(requisitionKey('https://acme.com/careers/job/?gh_jid=123'),requisitionKey('https://job-boards.greenhouse.io/acme/jobs/123'));assert.notEqual(requisitionKey('https://job-boards.greenhouse.io/acme/jobs/123'),requisitionKey('https://job-boards.greenhouse.io/acme/jobs/124'));assert.notEqual(canonical('https://jobs.ashbyhq.com/acme/123'),canonical('https://jobs.ashbyhq.com/acme/124'));assert.equal(companyGroup('TikTok'),companyGroup('ByteDance'))});
test('New York midnight and spreadsheet formula escaping',()=>{assert.equal(nyDay(new Date('2026-09-12T02:00:00Z')),'2026-09-11');assert.equal(safeCsv('=HYPERLINK("evil")'),'"\'=HYPERLINK(""evil"")"')});

test('saved salary threshold determines eligibility after the owner lowers it',()=>{const job={...valid,salaryMin:100000};assert.notEqual(evaluate(job,{...defaultRules,minBase:120000}).state,'ready');assert.equal(evaluate(job,defaultRules).state,'ready');assert.notEqual(evaluate({...job,checks:{...job.checks,base:{...check,value:'fail'}}},defaultRules).state,'ready')});

test('blocked applications do not starve the queue and only resume when targeted',()=>{const a={job_id:'j1',status:'blocked'};assert.equal(claimableApplication(a,at),false);assert.equal(claimableApplication(a,at,'j1'),true);assert.equal(claimableApplication(a,at,'j2'),false);assert.equal(claimableApplication({...a,status:'uncertain'},at,'j1'),false);assert.equal(claimableApplication({...a,status:'submitted'},at,'j1'),false);assert.equal(claimableApplication({...a,status:'queued'},at),true);assert.equal(claimableApplication({...a,status:'processing',lease_until:'2020-01-01'},at),true);assert.equal(claimableApplication({...a,status:'processing',lease_until:null},at),false)});
