'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {ArrowUpRight} from 'lucide-react';
import {careerLane} from '@/lib/career-filters';

const stages:Record<string,string>={queued:'计划投递',submitted:'已投递',assessment:'测评',interview:'面试',offer:'Offer',rejected:'未通过',withdrawn:'已撤回',uncertain:'待确认',blocked:'需处理'};
export default function AgentRecommendations({recommendations,applications,members,profiles,currentEmail,collaborative=true,busy,act}:{recommendations:any[];applications:any[];members:any[];profiles:any[];currentEmail:string;collaborative?:boolean;busy:boolean;act:(action:string,payload:any,success:string)=>Promise<any>}){
 const [showSkipped,setShowSkipped]=useState(false);
 const [typeFilter,setTypeFilter]=useState<'all'|'full_time'|'summer_intern'>('all');
 const name=(email:string)=>members.find(member=>member.email===email)?.name||email;
 const agentItems=recommendations.filter(item=>item.source_kind==='agent');
 const visible=agentItems.filter(item=>(typeFilter==='all'||item.opportunity_type===typeFilter)&&(showSkipped||item.myDecision!=='skip'));
 const myTargetType=profiles.find(profile=>profile.member_email===currentEmail).target_type;
 return <><div className="page-heading"><div><p className="eyebrow">AGENT PICKS</p><h1>{collaborative?'共享岗位':'岗位推荐'}</h1><p className="muted">Agent 会区分全职与暑期实习；你决定是否加入自己的申请计划。</p></div></div><div className="section-heading"><span className="pill">{agentItems.length} 条 Agent 推荐</span>{agentItems.some(item=>item.myDecision==='skip')&&<Button variant="ghost" size="sm" onClick={()=>setShowSkipped(!showSkipped)}>{showSkipped?'隐藏已跳过':'查看已跳过'}</Button>}</div><div className="buttons mb-4"><button className={typeFilter==='all'?'map-choice active':'map-choice'} onClick={()=>setTypeFilter('all')}>全部</button><button className={typeFilter==='full_time'?'map-choice active':'map-choice'} onClick={()=>setTypeFilter('full_time')}>全职</button><button className={typeFilter==='summer_intern'?'map-choice active':'map-choice'} onClick={()=>setTypeFilter('summer_intern')}>暑期实习</button></div><section className="panel">{visible.map(item=>{const participants=applications.filter(application=>application.url===item.url);const mine=participants.some(application=>application.memberEmail===currentEmail);const eligible=(!item.target_email||item.target_email===currentEmail)&&item.opportunity_type===myTargetType;return <article className="team-recommendation" key={item.id}><div className="section-heading"><div><p className="eyebrow">{item.target_email?`推荐给 ${name(item.target_email)}`:item.coapply?'建议符合目标的成员申请':'供成员考虑'} · {item.opportunity_type==='summer_intern'?'暑期实习':'全职'} · {item.period} · {name(item.author_email)} 的 Agent</p><h3>{item.company} · {item.title}</h3></div><a className="button-link" href={item.url} target="_blank" rel="noreferrer">官方岗位 <ArrowUpRight size={14}/></a></div><p className="muted">{item.location||'地点待核实'} · {careerLane(item)}</p><p>{item.note}</p><p className="muted">依据：{item.evidence}</p><p className="muted">{participants.length?participants.map(application=>name(application.memberEmail)+'：'+(stages[application.status]||application.status)).join(' · '):'尚未加入申请计划'}</p><div className="buttons mt-4"><Button size="sm" disabled={busy||mine||!eligible} onClick={()=>act('plan.add',{recommendationId:item.id},'已加入你的申请计划')}>{mine?'已在我的申请中':eligible?'加入我的申请':'不匹配我的求职目标'}</Button>{item.myDecision==='skip'?<Button size="sm" variant="outline" disabled={busy} onClick={()=>act('recommendation.restore',{id:item.id},'已恢复推荐')}>恢复推荐</Button>:<Button size="sm" variant="ghost" disabled={busy} onClick={()=>act('recommendation.dismiss',{id:item.id},'已跳过')}>不考虑</Button>}</div></article>})}{!visible.length&&<p className="empty-copy">Agent 尚未给出带依据的岗位推荐。把使用引导中的指令交给自己的 Agent，让它读取资料、核实官网并写入推荐。普通候选岗位不计作 Agent 推荐。</p>}</section></>;
}
