'use client';
import {t as tr,useLanguage,dateLocale} from '@/lib/i18n';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';

const date=(value:string)=>new Date(value).toLocaleDateString(dateLocale(),{timeZone:'America/New_York',year:'numeric',month:'short',day:'numeric'});
export default function AgentRoom({collaborative=true,notes,tasks,requests,person,busy,act}:{collaborative?:boolean;notes:any[];tasks:any[];requests:any[];person:(email:string)=>string;busy:boolean;act:(action:string,payload:any,success:string)=>Promise<any>}){
 useLanguage();
 const [request,setRequest]=useState('');
 return <><div className="page-heading"><div><p className="eyebrow">AGENT ROOM</p><h1>{tr("Agent 信息")}</h1><p className="muted">{tr("这里只展示 Agent 真正留下的发现、依据和下一步。人的要求不会混入 Agent 发言。")}</p></div></div><div className="team-grid"><section className="panel"><h2>{tr("Agent 的有效信息")}</h2>{notes.map(note=><article className="agent-insight" key={note.id}><div className="section-heading"><strong>{person(note.member_email)} {tr("的 Agent")}</strong><small>{date(note.created)}</small></div><h3>{note.finding}</h3><p><strong>{tr("依据")}</strong> · {note.evidence}</p><p><strong>{tr("下一步")}</strong> · {note.nextAction}</p>{note.sourceUrl&&<a href={note.sourceUrl} target="_blank" rel="noreferrer">{tr("查看来源 ↗")}</a>}</article>)}{!notes.length&&<p className="empty-copy">{tr("Agent 尚未留下有依据的发现。")}</p>}</section><div><section className="panel"><h2>{tr("给 Agent 的研究要求")}</h2><p className="muted">{tr("要求保存后，请把它交给自己的 Agent 执行。网页不会自动唤醒或运行 Agent。")}</p><form className="team-form" onSubmit={async event=>{event.preventDefault();if(await act('agent.request',{content:request},tr("要求已记录，等待 Agent 阅读")))setRequest('')}}><Textarea aria-label={tr("给 Agent 的要求")} rows={3} value={request} onChange={event=>setRequest(event.target.value)} placeholder={tr("例如：按我的技能与目标时间推荐纽约 Applied AI 岗位，附上官网依据")}/><Button type="submit" disabled={busy||!request.trim()}>{tr("记录要求")}</Button></form><p className="muted">{tr("我发出的要求：")}{requests.length} {tr("条")}</p></section><section className="panel"><h2>{collaborative?tr("成员任务"):tr("我的 Agent 任务")}</h2>{tasks.filter(task=>task.status!=='done').slice(0,8).map(task=><div className="team-row" key={task.id}><div><strong>{task.title}</strong><p className="muted">{task.details}</p></div><span className="pill">{task.status==='doing'?tr("进行中"):tr("待处理")}</span></div>)}{!tasks.some(task=>task.status!=='done')&&<p className="empty-copy">{tr("暂无未完成的任务。")}</p>}</section></div></div></>;
}
