'use client';
import {t as tr,useLanguage} from '@/lib/i18n';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';

export default function CareerProfiles({profiles,members,currentEmail,editRequested=0,busy,save}:{profiles:any[];members:any[];currentEmail:string;editRequested?:number;busy:boolean;save:(profile:any)=>Promise<any>}){
 useLanguage();
 const [editing,setEditing]=useState<any>(null);
 useEffect(()=>{if(editRequested){const profile=profiles.find(item=>item.member_email===currentEmail);setEditing({headline:profile.headline,location:profile.location,focus:profile.focus,skills:profile.skills,startDate:profile.start_date,targetType:profile.target_type})}},[editRequested]);
 const name=(email:string)=>members.find(member=>member.email===email)?.name||email;
 return <><div className="team-grid">{profiles.map(profile=><section className="panel career-profile" key={profile.member_email}><div className="section-heading"><h2>{name(profile.member_email)}</h2>{profile.member_email===currentEmail&&<Button variant="outline" size="sm" onClick={()=>setEditing({headline:profile.headline,location:profile.location,focus:profile.focus,skills:profile.skills,startDate:profile.start_date,targetType:profile.target_type})}>{tr("编辑我的资料")}</Button>}</div><p>{profile.headline||tr("尚未填写求职简介")}</p><div className="career-profile-facts"><span>{tr("求职类型：")}{profile.target_type==='summer_intern'?tr("暑期实习"):tr("全职")}</span><span>{tr("地区：")}{profile.location||tr("待补充")}</span><span>{tr("目标方向：")}{profile.focus||tr("待补充")}</span><span>{tr("技能：")}{profile.skills||tr("待补充")}</span><span>{tr("目标时间：")}{profile.start_date||tr("待补充")}</span></div></section>)}</div>{editing&&<div className="team-modal-backdrop" role="presentation" onClick={()=>setEditing(null)}><div className="team-modal panel" role="dialog" aria-modal="true" aria-label={tr("编辑我的求职资料")} onClick={event=>event.stopPropagation()}><h2>{tr("我的求职资料")}</h2><p className="muted">{tr("Agent 用这些目标匹配岗位；联系方式和身份答案在个人申请资料中单独确认。")}</p><form className="team-form" onSubmit={async event=>{event.preventDefault();if(await save(editing))setEditing(null)}}><label>{tr("求职类型")}<select value={editing.targetType} onChange={event=>setEditing({...editing,targetType:event.target.value})}><option value="full_time">{tr("全职")}</option><option value="summer_intern">{tr("暑期实习")}</option></select></label><label>{tr("一句话介绍")}<Input value={editing.headline} onChange={event=>setEditing({...editing,headline:event.target.value})}/></label><label>{tr("所在地 / 期望地区")}<Input value={editing.location} onChange={event=>setEditing({...editing,location:event.target.value})}/></label><label>{tr("目标岗位方向")}<Input value={editing.focus} onChange={event=>setEditing({...editing,focus:event.target.value})}/></label><label>{tr("技能与经验关键词")}<Textarea rows={3} value={editing.skills} onChange={event=>setEditing({...editing,skills:event.target.value})}/></label><label>{tr("期望入职 / 实习时间")}<Input value={editing.startDate} onChange={event=>setEditing({...editing,startDate:event.target.value})}/></label><div className="buttons"><Button type="submit" disabled={busy}>{tr("保存资料")}</Button><Button type="button" variant="outline" onClick={()=>setEditing(null)}>{tr("取消")}</Button></div></form></div></div>}</>;
}
