'use client';
import {t as tr,useLanguage} from '@/lib/i18n';
import {useState,useRef,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Check,Copy,FileText,UserRound,MessageCircle,Users,BriefcaseBusiness} from 'lucide-react';
import {toast} from 'sonner';

export default function GettingStarted({data,open,busy,act}:{data:any;open:(view:string,section?:string)=>void;busy:boolean;act:(action:string,payload:any,message?:string)=>Promise<any>}){
 useLanguage();
 const [promptKind,setPrompt]=useState('');const promptRef=useRef<HTMLElement>(null);
 const solo=data.preferences.mode==='solo',me=data.me,profile=data.profiles.find((item:any)=>item.member_email===me.email);
 const ownFiles=data.files.filter((item:any)=>item.memberEmail===me.email);
 const profileReady=!!(profile.headline&&profile.focus&&profile.start_date);
 const agentReady=data.agentNotes.some((item:any)=>item.member_email===me.email);
 const recommendationReady=data.recommendations.some((item:any)=>item.target_email===me.email||!item.target_email);
 const agentPrompt=tr("请接手我的本地 AI 求职工作台。代码库：https://github.com/Cornelius-Chen/AI-Career-Workbench 。先读 AGENTS.md、docs/GETTING-STARTED.md 和 docs/LOCAL-WORKBENCH.md。当前成员：{0}，模式：{1}。入口：{2} 。\n\n如果尚未安装，在一个新目录克隆代码、npm ci、npm run local:setup -- --name \"我的名字\"、npm run local:start；单人安装无需 GitHub 登录或邀请文件。已有 .local/ 时保留全部数据。\n\n启动后用 npm run local:agent -- context 读取真实资料与已有信息。{3}结合我上传的 PDF / DOCX 简历和我本人确认的信息，整理求职简介；不要猜测联系方式、学校、成绩、经验、工作授权或身份答案。完整申请资料与经历在“我的工作台 → 简历与个人资料”由我确认，原始简历不要直接当作已确认事实。\n\n查官方招聘页面，核实开放状态、岗位类型、目标时间和匹配理由，通过 local:agent 的 note、recommend、task 命令写入有依据的发现和推荐。推荐指定 context 中的 currentMemberEmail，不写死其他人的邮箱或年份。让我选择加入申请计划或跳过。没有官网成功页、申请编号或确认邮件，不记录为已投递。\n\n个人资料和密钥不进公开 GitHub。{4}网页中的“记录要求”只保存待办，不会自动唤醒你；请实际执行，再报告完成项和剩余项。", me.name, solo?tr("单人"):tr("协作"), data.entryUrl, solo?tr("单人模式只处理我的资料。"):tr("先用 npm run local:sync 拉取伙伴更新，分别核对每个成员的求职类型、地区和入职年份。"), solo?tr("不要创建或使用共享仓库。"):tr("完成后运行 npm run local:sync；冲突保留双方内容并交给本人选择。"));
 const collaborationPrompt=tr("请帮我{0}。先读 docs/LOCAL-WORKBENCH.md，保留现有 .local/、数据库与文件。{1}邀请成员使用 local:invite；私下发送生成的 .local/invitations/成员/ 安装目录，等待对方接受邀请并在自己的电脑安装。不要公开安装密钥。每人自己补全目标和简历共享选择，首次上传/拉取后核对页面。需要改程序时再配置相应代码仓库的协作者权限，数据协作邀请不会自动授予公开源码写入权限。", data.syncConfigured?tr("管理已有协作空间并邀请新成员"):tr("从单人工作台开启可选协作"), data.syncConfigured?tr("已有私有数据仓库，直接使用 npm run local:invite -- --login 伙伴的GitHub用户名。"):tr("由我完成 gh auth login；保持网站运行，执行 npm run local:share -- --repo 我的GitHub用户名/一个新的私有数据仓库名；然后关闭并重启工作台。"));
 const prompt=promptKind==='agent'?agentPrompt:promptKind==='collaboration'?collaborationPrompt:'';
 useEffect(()=>{if(promptKind)promptRef.current!.scrollIntoView({behavior:'smooth',block:'start'})},[promptKind]);
 const steps=[
  {title:tr("填写求职目标"),description:tr("填写简介、地区、方向和时间。全职与暑期实习分别匹配，年份由你指定。"),done:profileReady,icon:UserRound,button:tr("编辑求职目标"),run:()=>open('mine','profile')},
  {title:tr("上传简历，确认个人资料"),description:tr("上传 PDF / DOCX 原始简历。申请邮箱、联系方式、授权答案和经历事实由你核对。"),done:ownFiles.length>0,icon:FileText,button:tr("上传简历"),run:()=>open('files')},
  {title:tr("交给自己的 Agent 研究"),description:tr("复制下面的指令给 Codex / ChatGPT Agent。它会读资料、核实官网岗位并留下依据。这里不会自动运行 Agent。"),done:agentReady,icon:MessageCircle,button:tr("获取 Agent 指令"),run:()=>setPrompt('agent')},
  {title:tr("选择岗位，跟踪真实进度"),description:tr("在岗位推荐中选择加入申请计划或跳过。提交成功后记录官方证据，再更新申请状态。"),done:recommendationReady,icon:BriefcaseBusiness,button:tr("查看推荐岗位"),run:()=>open('recommendations')}
 ];
 return <><div className="page-heading"><div><p className="eyebrow">GET STARTED</p><h1>{tr("把工作台用起来")}</h1><p className="muted">{tr("先完成自己的资料与岗位研究；有需要时再邀请伙伴。")}</p></div><span className="pill">{steps.filter(step=>step.done).length} {tr("/ 4 项已有记录")}</span></div><div className="onboarding-steps">{steps.map((step,index)=><section className="panel onboarding-step" key={step.title}><div className="onboarding-number">{step.done?<Check size={20}/>:String(index+1).padStart(2,'0')}</div><div><h2>{step.title}</h2><p className="muted">{step.description}</p><Button variant="outline" size="sm" onClick={step.run}><step.icon size={16}/>{step.button}</Button></div></section>)}</div><section className="panel"><div className="section-heading"><div><h2>{tr("申请资料放在哪里？")}</h2><p className="muted">{tr("求职目标用于匹配岗位，申请资料用于填写正式表格，两者分开确认。")}</p></div><Button variant="outline" onClick={()=>me.role==='owner'?open('mine','materials'):setPrompt('agent')}>{me.role==='owner'?tr("打开个人资料"):tr("让 Agent 整理资料")}</Button></div><p className="muted">{tr("原始简历 →「简历与文件」；经历、联系方式与投递规则 →「我的工作台 → 简历与个人资料」；研究发现 →「Agent 信息」；官网确认与状态 →「我的申请」。上传简历本身不表示已经解析、核实或开始投递。")}</p>{me.role!=='owner'&&<p className="muted">{tr("协作成员在自己的文件区保存原始材料，Agent 据本人确认的信息整理求职简介；完整私人经历管理当前在独立单人工作台提供。")}</p>}</section><section className="panel"><div className="section-heading"><div><h2>{tr("单人或协作，由你选择")}</h2><p className="muted">{tr("当前：")}{solo?tr("单人使用"):tr("协作空间")}{tr("。切换只改变本机使用范围，原有记录保留。")}</p></div><Button variant="outline" onClick={()=>open('settings')}><Users size={16}/>{tr("空间设置")}</Button></div><p className="muted">{tr("单人模式只显示自己的资料，不上传或拉取共享更新。协作支持两人或更多成员，每位成员独立选择简历是否共享；过去已经共享的文件无法收回。")}</p><Button variant="ghost" onClick={()=>setPrompt('collaboration')}>{data.syncConfigured?tr("获取邀请伙伴指令"):tr("获取协作设置指令")}</Button></section>{prompt&&<section ref={promptRef} className="panel agent-prompt" aria-label={tr("交给 Agent 的指令")}><div className="section-heading"><h2>{tr("复制后发给自己的 Agent")}</h2><Button size="sm" onClick={async()=>{await navigator.clipboard.writeText(prompt);toast.success(tr("已复制，粘贴给你的 Agent 即可"))}}><Copy size={16}/>{tr("复制指令")}</Button></div><textarea aria-label={tr("Agent 使用指令")} rows={12} readOnly value={prompt}/><Button variant="ghost" onClick={()=>setPrompt('')}>{tr("收起")}</Button></section>}</>;
}

export function SpaceSettings({data,busy,act,guide}:{data:any;busy:boolean;act:(action:string,payload:any,message?:string)=>Promise<any>;guide:()=>void}){
 useLanguage();
 const mode=data.preferences.mode;
 return <><div className="page-heading"><div><p className="eyebrow">YOUR SPACE</p><h1>{tr("空间设置")}</h1><p className="muted">{tr("单人是默认选项，协作随时开启；成员数量不固定。")}</p></div></div><div className="mode-options">{[{id:'solo',title:tr("单人使用"),description:tr("自己的岗位、申请、简历和 Agent 信息。无需 GitHub 同步或邀请伙伴。")},{id:'collaboration',title:tr("协作空间"),description:tr("两人或多人交换岗位、申请进度和 Agent 发现，通过私有 GitHub 仓库加密同步。")}].map(item=><button className={'mode-option '+(mode===item.id?'selected':'')} aria-pressed={mode===item.id} disabled={busy} key={item.id} onClick={()=>act('workspace.mode',{mode:item.id},tr("使用模式已更新"))}><strong>{item.title}</strong><p>{item.description}</p><span>{mode===item.id?tr("当前模式"):tr("选择此模式")}</span></button>)}</div>{mode==='collaboration'&&<section className="panel"><h2>{data.syncConfigured?tr("协作成员"):tr("完成协作设置")}</h2><p className="muted">{data.syncConfigured?tr("已有私有同步仓库。成员各自保存、上传和拉取；程序更新需要拉取代码并重新构建。"):tr("选择协作不会自动公开资料。请把使用引导中的设置指令交给 Agent，创建私有数据仓库、邀请成员并安装后才能同步。")}</p>{data.members.map((member:any)=><div className="team-row" key={member.email}><div><strong>{member.name}{member.email===data.me.email?tr("（我）"):''}</strong><p className="muted">{member.resumeShared?tr("已允许共享简历"):tr("简历未共享")}</p></div></div>)}<Button variant="outline" onClick={guide}>{tr("查看设置与邀请指引")}</Button></section>}<section className="panel"><h2>{tr("资料与隐私")}</h2><p className="muted">{tr("本机数据库和文件保存在安装目录的 .local/ 中。更新代码时保留此目录。公开 GitHub 仓库仅保存程序；协作资料在上传前加密，密钥私下交给受邀成员。切回单人模式会停止本机同步，已发给其他成员的数据无法撤回。")}</p></section></>;
}
