'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {toast} from 'sonner';

const labels:Record<string,string>={jobs:'岗位',applications:'申请',events:'进度证据',files:'简历文件',team_members:'共享设置',team_profiles:'求职资料',team_recommendations:'推荐岗位',team_recommendation_decisions:'推荐选择',team_applications:'申请计划',team_application_events:'申请进度',team_files:'共享简历',team_messages:'Agent 信息',team_agent_tasks:'共同任务'};
const date=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN'):'尚未同步';
function summary(row:any){if(row===null)return '已移除';const detail=row.data?JSON.parse(row.data):row;return [row.company,detail.company,row.title,detail.title,row.status,detail.notes,detail.blockReason,row.headline,row.skills,row.content,row.resume_shared===undefined?'':row.resume_shared?'简历共享已开启':'简历共享已关闭'].filter(Boolean).join(' · ')||Object.entries(row).filter(([key])=>!['id','user_id','created','updated','data'].includes(key)).map(([key,value])=>String(value)).join(' · ')}
export default function LocalSyncControls({refresh}:{refresh:()=>Promise<any>}){
 const [status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{if(['127.0.0.1','localhost'].includes(location.hostname))fetch('/api/local-sync').then(response=>response.json()).then(setStatus)},[]);
 if(!status?.member)return null;
 const action=async(action:string,payload:any={})=>{setBusy(true);try{const response=await fetch('/api/local-sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const result=await response.json() as any;if(!response.ok)throw Error(result.error);setStatus(result.status);toast.success(result.message);if(action!=='upload')await refresh()}catch(error:any){toast.error(error.message)}finally{setBusy(false)}};
 return <section className="panel mb-6"><div className="section-heading"><div><strong>本地工作台 · {status.member}</strong><p className="muted">你和伙伴各用自己的电脑。保存先留在本机，上传后对方拉取才能看到。</p></div><div className="buttons"><Button size="sm" disabled={busy} onClick={()=>action('upload')}>上传我的更新</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>action('pull')}>拉取伙伴更新</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>action('sync')}>{busy?'同步中…':'双向同步'}</Button></div></div><small className="muted">上次上传：{date(status.lastUpload)} · 上次拉取：{date(status.lastPull)} · 数据存于成员私有仓库，上传前已加密。</small>{status.conflicts.length>0&&<div className="mt-5"><h3>{status.conflicts.length} 条记录有不同修改，请选择采用哪个版本</h3>{status.conflicts.map((conflict:any)=><article className="team-row" key={conflict.id}><div><strong>{labels[conflict.table]}</strong><p>本机：{summary(conflict.local)}</p><p>{conflict.author}：{summary(conflict.remote)}</p><div className="buttons"><Button disabled={busy} size="sm" onClick={()=>action('resolve',{id:conflict.id,choice:'local'})}>采用本机版本</Button><Button disabled={busy} size="sm" variant="outline" onClick={()=>action('resolve',{id:conflict.id,choice:'remote'})}>采用对方版本</Button></div></div></article>)}</div>}</section>;
}
