'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Switch} from '@/components/ui/switch';
import {toast,Toaster} from 'sonner';
import {ArrowUpRight,BriefcaseBusiness,FileText,Handshake,LayoutDashboard,ListChecks,MapPinned,MessageCircle,Plus,ShieldCheck,Users,UserRound} from 'lucide-react';
import JobMap from './job-map';
import {registerTeamTools} from '@/lib/team-webmcp';

const stages:Record<string,string>={queued:'计划投递',processing:'准备中',submitting:'提交中',uncertain:'待确认',blocked:'需处理',submitted:'已投递',assessment:'测评',interview:'面试',offer:'Offer',rejected:'未通过',withdrawn:'已撤回'};
const progressed=new Set(['submitted','assessment','interview','offer','rejected','withdrawn']);
const tabs=[['overview','总览',LayoutDashboard],['mine','我的工作台',UserRound],['recommendations','共享岗位',BriefcaseBusiness],['applications','双方申请',ListChecks],['map','岗位地图',MapPinned],['room','Agent 协作',MessageCircle],['files','简历共享',FileText]] as const;
const date=(value:string)=>new Date(value).toLocaleDateString('zh-CN',{timeZone:'America/New_York',year:'numeric',month:'short',day:'numeric'});

export default function TeamBoard(){
 const [data,setData]=useState<any>(null),[view,setView]=useState('overview'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({company:'',title:'',url:'',location:'',lane:'',note:''});
 const [selectedJob,setSelectedJob]=useState('');
 const [editing,setEditing]=useState<any>(null);
 const [message,setMessage]=useState(''),[taskForm,setTaskForm]=useState({title:'',details:'',assignedToEmail:''});
 const load=useCallback(async()=>{const response=await fetch('/api/team',{cache:'no-store'});const body:any=await response.json();if(!response.ok)throw Error(body.error);setData(body);return body},[]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 const act=async(action:string,payload:any={},message='已保存')=>{
  setBusy(true);
  try{const response=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const body:any=await response.json();if(!response.ok)throw Error(body.error);await load();toast.success(message);return body}
  catch(e:any){toast.error(e.message);return null}
  finally{setBusy(false)}
 };
 useEffect(()=>{const timer=setInterval(()=>load().catch(()=>{}),30000);return()=>clearInterval(timer)},[load]);
 useEffect(()=>registerTeamTools(async(action,payload)=>{const response=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const body:any=await response.json();if(!response.ok)throw Error(body.error);return body},load),[load]);
 const members=data?.members||[];
 const applications=data?.applications||[];
 const recommendations=data?.recommendations||[];
 const messages=data?.messages||[];
 const agentTasks=data?.agentTasks||[];
 const stats=useMemo(()=>members.map((member:any)=>{
  const mine=applications.filter((a:any)=>a.memberEmail===member.email);
  const submitted=mine.filter((a:any)=>progressed.has(a.status)||a.events?.some((e:any)=>e.accepted!==false&&e.stage==='submitted')).length;
  const interview=mine.filter((a:any)=>['interview','offer'].includes(a.status)||a.events?.some((e:any)=>e.accepted!==false&&e.stage==='interview')).length;
  const offers=mine.filter((a:any)=>a.status==='offer'||a.events?.some((e:any)=>e.accepted!==false&&e.stage==='offer')).length;
  return {...member,total:mine.length,submitted,interview,offers,interviewRate:submitted?Math.round(interview/submitted*100):null,offerRate:submitted?Math.round(offers/submitted*100):null};
 }),[members,applications]);
 if(!data)return <main className="loading-page"><Users size={38}/><h1>双人求职空间</h1><p className="muted">{error||'正在读取共享记录…'}</p></main>;
 const me=data.me;
 const person=(email:string)=>members.find((m:any)=>m.email===email)?.name||email;
 const ownFiles=data.files.filter((f:any)=>f.memberEmail===me.email);
 const otherFiles=data.files.filter((f:any)=>f.memberEmail!==me.email);
 const recommend=async(e:React.FormEvent)=>{e.preventDefault();const r=await act('recommendation.add',selectedJob?{jobId:selectedJob,note:form.note}:form,'已推荐给双方');if(r){setForm({company:'',title:'',url:'',location:'',lane:'',note:''});setSelectedJob('')}};
 const upload=async(file:File)=>{setBusy(true);try{const form=new FormData();form.append('file',file);const response=await fetch('/api/team/files',{method:'POST',body:form});const body:any=await response.json();if(!response.ok)throw Error(body.error);await load();toast.success('简历已加密保存')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const statCard=(s:any)=><section className="panel team-person" key={s.email}><div className="section-heading"><div><p className="eyebrow">{s.email===me.email?'我的进度':'伙伴进度'}</p><h2>{s.name}</h2></div><span className="pill">{s.total} 个岗位</span></div><div className="team-numbers"><div><strong>{s.submitted}</strong><span>已投递</span></div><div><strong>{s.interview}</strong><span>进入面试</span></div><div><strong>{s.offers}</strong><span>Offer</span></div></div><p className="muted">面试率 {s.interviewRate===null?'暂无数据':s.interviewRate+'%'} · Offer 成功率 {s.offerRate===null?'暂无数据':s.offerRate+'%'}</p><small className="muted">按已投递岗位计算；计划投递不计入分母。</small></section>;
 return <div className="team-shell"><Toaster richColors position="top-right"/><header className="team-header"><div className="team-logo"><div className="brand-mark"><Handshake size={20}/></div><div><strong>AI 求职工作台</strong><small>双人协作空间</small></div></div><nav aria-label="协作导航">{tabs.map(([id,label,Icon])=><button key={id} type="button" className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="team-account"><span>{me.name}</span><a href="/api/auth/signout?return_to=/team" target="_top">退出</a></div></header><main className="team-main">
 {view==='overview'&&<><div className="page-heading"><div><p className="eyebrow">TOGETHER, INDIVIDUALLY</p><h1>一起找机会，各自记录进展。</h1><p className="muted">相隔两地也能看到对方的岗位、投递详情和进度。申请仍由每个人分别提交。</p></div><Button onClick={()=>setView('recommendations')}><Plus size={16}/> 推荐岗位</Button></div><div className="team-grid">{stats.map(statCard)}</div><div className="team-grid"><section className="panel"><div className="section-heading"><h2>最近申请</h2><Button variant="ghost" onClick={()=>setView('applications')}>查看全部 <ArrowUpRight size={15}/></Button></div>{applications.slice(0,6).map((a:any)=><div className="team-row" key={a.id}><div><strong>{a.company} · {a.title}</strong><p className="muted">{person(a.memberEmail)} · 更新于 {date(a.updated)}</p></div><span className="pill">{stages[a.status]||a.status}</span></div>)}{!applications.length&&<p className="empty-copy">双方还没有申请记录。</p>}</section><section className="panel"><div className="section-heading"><h2>共同关注</h2><Button variant="ghost" onClick={()=>setView('recommendations')}>查看岗位 <ArrowUpRight size={15}/></Button></div>{recommendations.filter((r:any)=>r.coapply).slice(0,5).map((r:any)=><div className="team-row" key={r.id}><div><strong>{r.company} · {r.title}</strong><p className="muted">{person(r.author_email)} 推荐</p></div><Handshake size={17}/></div>)}{!recommendations.some((r:any)=>r.coapply)&&<p className="empty-copy">推荐一个岗位并标记“建议共同投递”，就会出现在这里。</p>}</section></div></>}
 {view==='mine'&&<><div className="page-heading"><div><p className="eyebrow">MY WORKBENCH</p><h1>我的工作台</h1><p className="muted">你的申请、待办和简历集中在这里；共享内容仍在旁边的协作栏目。</p></div>{me.role==='owner'&&<a className="button-link" href="/">打开完整个人工作台 <ArrowUpRight size={15}/></a>}</div><div className="team-grid">{stats.filter((s:any)=>s.email===me.email).map(statCard)}<section className="panel"><h2>我的协作任务</h2>{agentTasks.filter((t:any)=>!t.assigned_to_email||t.assigned_to_email===me.email).slice(0,6).map((t:any)=><div className="team-row" key={t.id}><div><strong>{t.title}</strong><p className="muted">{t.details}</p></div><span className="pill">{t.status==='done'?'完成':t.status==='doing'?'进行中':'待处理'}</span></div>)}{!agentTasks.length&&<p className="empty-copy">暂无共享任务。</p>}<Button variant="outline" size="sm" onClick={()=>setView('room')}>打开 Agent 协作区</Button></section></div><section className="panel mt-5"><div className="section-heading"><h2>我的申请</h2><Button variant="ghost" onClick={()=>setView('applications')}>查看双方申请 <ArrowUpRight size={15}/></Button></div>{applications.filter((a:any)=>a.memberEmail===me.email).slice(0,15).map((a:any)=><div className="team-row" key={a.id}><div><strong>{a.company} · {a.title}</strong><p className="muted">{a.location||'地点未注明'} · {date(a.updated)}</p></div><span className="pill">{stages[a.status]||a.status}</span></div>)}</section></>}
 {view==='recommendations'&&<><div className="page-heading"><div><p className="eyebrow">SHARED OPPORTUNITIES</p><h1>共享岗位</h1><p className="muted">推荐给对方、一起研究；每个人再决定是否加入自己的投递计划。</p></div></div><section className="panel"><h2>推荐一个岗位</h2><form className="team-form" onSubmit={recommend}><label>从现有岗位选择<select value={selectedJob} onChange={e=>setSelectedJob(e.target.value)}><option value="">手动填写新岗位</option>{data.jobs.map((j:any)=><option key={j.id} value={j.id}>{j.company} · {j.title}</option>)}</select></label>{!selectedJob&&<><div className="team-form-grid"><label>公司<Input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label>岗位<Input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>官方岗位链接<Input type="url" required value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label></div><div className="team-form-grid"><label>工作地点<Input required placeholder="例如 New York, NY" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>岗位类型<Input required placeholder="例如 AI / ML / Data / FDE" value={form.lane} onChange={e=>setForm({...form,lane:e.target.value})}/></label></div></>}<label>推荐理由 / 需要核实的地方<Textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><Button type="submit" disabled={busy}><Plus size={16}/> 推荐给对方</Button></form></section><section className="panel"><h2>你们推荐的岗位</h2>{recommendations.map((r:any)=>{const participants=applications.filter((a:any)=>a.url===r.url);const mine=participants.some((a:any)=>a.memberEmail===me.email);return <article className="team-recommendation" key={r.id}><div className="section-heading"><div><p className="eyebrow">{r.coapply?'建议共同投递':'共享线索'} · {person(r.author_email)} 推荐</p><h3>{r.company} · {r.title}</h3></div><a className="button-link" href={r.url} target="_blank" rel="noreferrer">官方链接 <ArrowUpRight size={14}/></a></div><p className="muted">{r.location} · {r.lane}</p>{r.note&&<p className="muted">{r.note}</p>}<p className="muted">{participants.length?participants.map((a:any)=>person(a.memberEmail)+'：'+(stages[a.status]||a.status)).join(' · '):'双方尚未加入投递计划'}</p><div className="buttons"><Button size="sm" disabled={busy||mine} onClick={()=>act('plan.add',{recommendationId:r.id},'已加入你的投递计划')}>{mine?'已在我的计划':'加入我的计划'}</Button>{!r.coapply&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>act('recommendation.coapply',{id:r.id},'已标记为建议共同投递')}><Handshake size={15}/> 建议共同投递</Button>}</div></article>})}{!recommendations.length&&<p className="empty-copy">还没有共享岗位。你可以从现有岗位中挑一个，也可以贴新的官方链接。</p>}</section></>}
 {view==='applications'&&<><div className="page-heading"><div><p className="eyebrow">APPLICATIONS</p><h1>双方申请进度</h1><p className="muted">公司、岗位、申请详情和进度双方可见；每个人只能修改自己的记录。</p></div></div><div className="team-grid">{stats.map(statCard)}</div><section className="panel">{applications.map((a:any)=><article className="team-application" key={a.id}><div className="section-heading"><div><p className="eyebrow">{person(a.memberEmail)} · {date(a.updated)}</p><h3>{a.company} · {a.title}</h3></div><span className="pill">{stages[a.status]||a.status}</span></div><a href={a.url} target="_blank" rel="noreferrer">官方岗位 <ArrowUpRight size={14} className="inline"/></a>{a.notes&&<p className="muted mt-3 whitespace-pre-wrap">{a.notes}</p>}{a.reference&&<p className="muted">申请编号：{a.reference}</p>}{a.deadline&&<p className="muted">截止时间：{date(a.deadline)}</p>}{a.lastEvidence&&<p className="notice mt-3">{a.lastEvidence}</p>}{a.events?.length>0&&<details className="mt-3"><summary>申请详情与时间线（{a.events.length}）</summary>{a.events.map((e:any)=><div className="timeline-event" key={e.id}><strong>{stages[e.stage]||e.stage||'进度'} · {date(e.created)}</strong><p className="muted whitespace-pre-wrap">{e.evidence||e.details||'已记录状态'}</p>{e.sourceUrl&&<a href={e.sourceUrl} target="_blank" rel="noreferrer">查看来源 ↗</a>}</div>)}</details>}{a.memberEmail===me.email&&(a.legacy?<a className="button-link mt-3" href="/">在个人工作台更新</a>:<Button className="mt-3" variant="outline" size="sm" onClick={()=>setEditing({...a,details:''})}>更新我的进度</Button>)}</article>)}{!applications.length&&<p className="empty-copy">还没有申请记录。先到“共享岗位”推荐并加入计划。</p>}</section></>}
 {view==='map'&&<><div className="page-heading"><div><p className="eyebrow">OPPORTUNITY MAP</p><h1>岗位地图</h1><p className="muted">按岗位类型给美国各地区着色，切换推荐与已投递岗位。点击气泡查看岗位。</p></div></div><JobMap recommendations={recommendations} applications={applications} jobs={data.jobs}/></>}
 {view==='room'&&<><div className="page-heading"><div><p className="eyebrow">SHARED AGENT ROOM</p><h1>双方 Agent 协作区</h1><p className="muted">这里的消息和任务对双方可见。Agent 可以读取并写入这块共享板；消息会标明是本人还是 Agent 发布。</p></div></div><div className="team-grid"><section className="panel"><h2>共享消息</h2><form className="team-form" onSubmit={async e=>{e.preventDefault();const r=await act('message.post',{content:message,authorKind:'person'},'消息已发到共享空间');if(r)setMessage('')}}><label>写给对方和两边 Agent<Textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="例如：请一起看看纽约的 Applied AI 岗位"/></label><Button type="submit" disabled={busy||!message.trim()}>发送消息</Button></form><div className="team-room-feed">{messages.map((item:any)=><article key={item.id} className="team-message"><div><strong>{person(item.member_email)}{item.author_kind==='agent'?' 的 Agent':''}</strong><small>{date(item.created)}</small></div><p className="whitespace-pre-wrap">{item.content}</p></article>)}{!messages.length&&<p className="empty-copy">这里还没有消息。</p>}</div></section><section className="panel"><h2>共同任务</h2><form className="team-form" onSubmit={async e=>{e.preventDefault();const r=await act('agent_task.create',{...taskForm,assignedToEmail:taskForm.assignedToEmail||null},'共享任务已创建');if(r)setTaskForm({title:'',details:'',assignedToEmail:''})}}><label>任务名称<Input required value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})}/></label><label>分配给<select value={taskForm.assignedToEmail} onChange={e=>setTaskForm({...taskForm,assignedToEmail:e.target.value})}><option value="">双方</option>{members.map((member:any)=><option key={member.email} value={member.email}>{member.name}</option>)}</select></label><label>说明<Textarea rows={2} value={taskForm.details} onChange={e=>setTaskForm({...taskForm,details:e.target.value})}/></label><Button type="submit" disabled={busy}>创建任务</Button></form><div className="team-room-feed">{agentTasks.map((task:any)=><article className="team-message" key={task.id}><div><strong>{task.title}</strong><small>{task.assigned_to_email?person(task.assigned_to_email):'双方'} · {date(task.updated)}</small></div>{task.details&&<p className="muted whitespace-pre-wrap">{task.details}</p>}<select value={task.status} disabled={busy} onChange={e=>act('agent_task.update',{id:task.id,status:e.target.value},'任务状态已更新')}><option value="open">待处理</option><option value="doing">进行中</option><option value="done">已完成</option></select></article>)}{!agentTasks.length&&<p className="empty-copy">还没有共享任务。</p>}</div></section></div></>}
 {view==='files'&&<><div className="page-heading"><div><p className="eyebrow">RESUME PRIVACY</p><h1>简历共享</h1><p className="muted">共享开关由每个人自行控制；关闭时对方无法查看或下载你的简历。</p></div></div><section className="panel"><div className="rule-row"><div><h2>允许对方查看我的全部简历</h2><p className="muted">包含你已上传和生成的简历文件。默认关闭，随时可以撤销。</p></div><Switch aria-label="共享我的全部简历" checked={me.resumeShared} disabled={busy} onCheckedChange={enabled=>act('resume.share',{enabled},enabled?'简历共享已开启':'简历共享已关闭')}/></div><div className="section-heading mt-6"><div><h2>我的文件</h2><p className="muted">在这里新上传的文件使用 AES-GCM 加密保存。</p></div><label className="button-link cursor-pointer"><Plus size={15}/> 上传 PDF / DOCX<input className="sr-only" type="file" accept=".pdf,.docx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file);e.currentTarget.value=''}}/></label></div>{ownFiles.map((f:any)=><div className="team-row" key={f.id}><div><strong>{f.name}</strong><p className="muted">{date(f.created)}</p></div><a className="button-link" href={f.url}>下载</a></div>)}{!ownFiles.length&&<p className="empty-copy">你还没有上传文件。</p>}</section><section className="panel"><h2>对方已共享的文件</h2>{otherFiles.map((f:any)=><div className="team-row" key={f.id}><div><strong>{f.name}</strong><p className="muted">{person(f.memberEmail)} · {date(f.created)}</p></div><a className="button-link" href={f.url}>下载</a></div>)}{!otherFiles.length&&<p className="empty-copy">对方尚未开启简历共享，或还没有文件。</p>}</section><p className="muted"><ShieldCheck size={15} className="inline"/> 只有已授权账号可以进入协作空间。</p></>}
 </main>{editing&&<div className="team-modal-backdrop" role="presentation" onClick={()=>setEditing(null)}><div className="team-modal panel" role="dialog" aria-modal="true" aria-label="更新申请进度" onClick={e=>e.stopPropagation()}><h2>更新我的申请</h2><p className="muted">{editing.company} · {editing.title}</p><form className="team-form mt-5" onSubmit={async e=>{e.preventDefault();const r=await act('application.update',{id:editing.id,status:editing.status,notes:editing.notes,details:editing.details},'申请进度已更新');if(r)setEditing(null)}}><label>当前进度<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}>{['queued','submitted','assessment','interview','offer','rejected','withdrawn'].map(status=><option key={status} value={status}>{stages[status]}</option>)}</select></label><label>申请详情 / 备注<Textarea rows={4} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><label>这次变化的证据或说明<Textarea rows={3} value={editing.details} onChange={e=>setEditing({...editing,details:e.target.value})}/></label><div className="buttons"><Button disabled={busy} type="submit">保存进度</Button><Button variant="outline" type="button" onClick={()=>setEditing(null)}>取消</Button></div></form></div></div>}</div>;
}
