import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import {Document,Paragraph,TextRun,Packer,HeadingLevel} from 'docx';
import {factLines} from './experiences';
import type {Fact} from './domain';
export function chooseFacts(facts:Fact[],job:any){const terms=new Set((job.title+' '+job.description.slice(0,1800)).toLowerCase().match(/[a-z][a-z0-9+#]{2,}/g)||[]);return facts.filter(f=>f.confirmed&&!f.historical).map(f=>({f,score:(f.text.toLowerCase().match(/[a-z][a-z0-9+#]{2,}/g)||[]).filter(t=>terms.has(t)).length})).sort((a,b)=>b.score-a.score).map(x=>x.f)}
export async function renderResume(profile:any,facts:Fact[]){if(!profile.confirmed||!profile.name||!profile.email)throw Error('先确认个人资料');if(!facts.length||facts.some(f=>!f.confirmed))throw Error('仅可使用已确认经历');
 const lines:{text:string,kind:string}[]=[{text:profile.name,kind:'title'},{text:[profile.email,profile.phone,profile.location,profile.linkedin,profile.github].filter(Boolean).join(' | '),kind:'contact'}];
 for(const cat of ['Education','Experience','Projects','Research','Publications','Skills']){const ff=facts.filter(f=>f.category===cat);if(!ff.length)continue;lines.push({text:cat.toUpperCase(),kind:'heading'});for(const f of ff)for(const text of factLines(f.text))lines.push({text,kind:'body'})}
 const doc=await PDFDocument.create();const page=doc.addPage([612,792]);const font=await doc.embedFont(StandardFonts.Helvetica);const bold=await doc.embedFont(StandardFonts.HelveticaBold);let y=748;
 for(const l of lines){const size=l.kind==='title'?21:l.kind==='heading'?11:10;const face=['title','heading'].includes(l.kind)?bold:font;const content=l.text.replace(/\s+/g,' ').replace(/[–—]/g,'-').replace(/[‘’]/g,"'").replace(/[“”]/g,'"');try{face.encodeText(content)}catch{throw Error('英文简历含不支持的字符，请改用英文或常用标点')}
 if(l.kind==='heading')y-=12;let line='';const chunks:string[]=[];for(const word of content.split(/\s+/)){const next=line?line+' '+word:word;if(face.widthOfTextAtSize(next,size)>516){if(!line||face.widthOfTextAtSize(word,size)>516)throw Error('简历含过长字段，请缩短链接或拆分文字');chunks.push(line);line=word}else line=next}if(line)chunks.push(line);for(const text of chunks){if(y<47)throw Error('内容超过一页，请减少所选经历或精简文字');page.drawText(text,{x:48,y,size,font:face,color:rgb(0.08,0.08,0.08)});y-=size*1.45}y-=5;}
 const paragraphs=lines.map(l=>new Paragraph({heading:l.kind==='title'?HeadingLevel.TITLE:l.kind==='heading'?HeadingLevel.HEADING_1:undefined,spacing:{after:l.kind==='heading'?90:100,before:l.kind==='heading'?150:0},keepNext:l.kind==='heading'||l.kind==='title',children:[new TextRun({text:l.text,font:'Arial',size:l.kind==='title'?42:l.kind==='heading'?22:20,bold:l.kind==='title'||l.kind==='heading',color:'111111'})]}));
 const word=new Document({styles:{default:{document:{run:{font:'Arial',size:20,color:'111111'},paragraph:{spacing:{line:260}}}}},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:880,bottom:880,left:960,right:960}}},children:paragraphs}]});return{pdf:await doc.save(),docx:await Packer.toBuffer(word),text:lines.map(l=>l.text).join('\n\n')};
}
