export function registerTeamTools(api:(action:string,payload:any)=>Promise<any>,reload:()=>Promise<any>){
 const context=(document as any).modelContext;
 if(!context?.registerTool)return()=>{};
 const abort=new AbortController();
 const tools=[
  {name:'read_shared_career_space',description:'Read both members career profiles, confirmed application summaries, candidate jobs, requests to agents, and the other agent factual notes. Do not infer an application was submitted from a queued or uncertain status. Resume contents are excluded.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const response=await fetch('/api/team?view=agent',{cache:'no-store'});return response.json()}},
  {name:'post_shared_career_message',description:'Publish a useful agent note for both people and agents. Include a concrete finding, the application/job/profile evidence used, and a specific next action. Do not post conversational filler or unsupported claims.',inputSchema:{type:'object',properties:{finding:{type:'string'},evidence:{type:'string'},nextAction:{type:'string'},sourceUrl:{type:'string'}},required:['finding','evidence','nextAction'],additionalProperties:false},execute:async(x:any)=>{const result=await api('agent.note',x);await reload();return result}},
  {name:'create_shared_career_task',description:'Create a task visible to both people and agents.',inputSchema:{type:'object',properties:{title:{type:'string'},details:{type:'string'},assignedToEmail:{type:'string'}},required:['title'],additionalProperties:false},execute:async(x:any)=>{const result=await api('agent_task.create',x);await reload();return result}},
  {name:'update_shared_career_task',description:'Update a shared task status to open, doing or done.',inputSchema:{type:'object',properties:{id:{type:'string'},status:{type:'string',enum:['open','doing','done']}},required:['id','status'],additionalProperties:false},execute:async(x:any)=>{const result=await api('agent_task.update',x);await reload();return result}},
  {name:'recommend_shared_job',description:'Recommend a verified job based on the two career profiles and application history. Explain the fit and cite concrete evidence. Use targetEmail for one person or leave it empty for both; coapply means both should consider applying separately.',inputSchema:{type:'object',properties:{jobId:{type:'string'},company:{type:'string'},title:{type:'string'},url:{type:'string'},location:{type:'string'},lane:{type:'string'},note:{type:'string'},evidence:{type:'string'},targetEmail:{type:'string'},coapply:{type:'boolean'}},required:['note','evidence'],additionalProperties:false},execute:async(x:any)=>{const result=await api('recommendation.agent',x);await reload();return result}}
 ];
 for(const tool of tools)Promise.resolve(context.registerTool(tool,{signal:abort.signal}));
 return()=>abort.abort();
}
