export function registerTeamTools(api:(action:string,payload:any)=>Promise<any>,reload:()=>Promise<any>){
 const context=(document as any).modelContext;
 if(!context?.registerTool)return()=>{};
 const abort=new AbortController();
 const tools=[
  {name:'read_shared_career_space',description:'Read current visible workspace members career profiles including target_type and start_date, confirmed application summaries, candidate jobs, requests to agents, and the other agent factual notes. Match full-time roles to full_time profiles and summer internships to summer_intern profiles. Do not infer an application was submitted from a queued or uncertain status. Resume contents are excluded.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const response=await fetch('/api/team?view=agent',{cache:'no-store'});return response.json()}},
  {name:'post_shared_career_message',description:'Publish a useful agent note for workspace members and agents. Include a concrete finding, the application/job/profile evidence used, and a specific next action. Do not post conversational filler or unsupported claims.',inputSchema:{type:'object',properties:{finding:{type:'string'},evidence:{type:'string'},nextAction:{type:'string'},sourceUrl:{type:'string'}},required:['finding','evidence','nextAction'],additionalProperties:false},execute:async(x:any)=>{const result=await api('agent.note',x);await reload();return result}},
  {name:'create_shared_career_task',description:'Create a task visible to workspace members and agents.',inputSchema:{type:'object',properties:{title:{type:'string'},details:{type:'string'},assignedToEmail:{type:'string'}},required:['title'],additionalProperties:false},execute:async(x:any)=>{const result=await api('agent_task.create',x);await reload();return result}},
  {name:'update_shared_career_task',description:'Update a shared task status to open, doing or done.',inputSchema:{type:'object',properties:{id:{type:'string'},status:{type:'string',enum:['open','doing','done']}},required:['id','status'],additionalProperties:false},execute:async(x:any)=>{const result=await api('agent_task.update',x);await reload();return result}},
  {name:'recommend_shared_job',description:'Recommend a verified job for one named member after checking their target_type and start_date. Set opportunityType to full_time or summer_intern from the official posting, and period to the posting season or start year. Cite concrete evidence for the type, timing and fit. Set coapply only when at least two workspace members seek the same opportunity type and season.',inputSchema:{type:'object',properties:{jobId:{type:'string'},company:{type:'string'},title:{type:'string'},url:{type:'string'},location:{type:'string'},lane:{type:'string'},note:{type:'string'},evidence:{type:'string'},targetEmail:{type:'string'},opportunityType:{type:'string',enum:['full_time','summer_intern']},period:{type:'string'},coapply:{type:'boolean'}},required:['note','evidence','targetEmail','opportunityType','period'],additionalProperties:false},execute:async(x:any)=>{const result=await api('recommendation.agent',x);await reload();return result}}
 ];
 for(const tool of tools)Promise.resolve(context.registerTool(tool,{signal:abort.signal}));
 return()=>abort.abort();
}
